from .eda_angle import EDA_ANGLE
from .vector2i import VECTOR2I
from .eda_item import EDA_ITEM


PCB_LAYER_ID = int


class BOARD_ITEM(EDA_ITEM):

    def SetParentGroup(self, aGroup: "PCB_GROUP") -> None:
        ...

    def GetParentGroup(self) -> "PCB_GROUP":
        ...

    def GetX(self) -> int:
        ...

    def GetY(self) -> int:
        ...

    def GetCenter(self) -> VECTOR2I:
        ...

    def SetX(self, aX: int) -> None:
        ...

    def SetY(self, aY: int) -> None:
        ...

    def IsConnected(self) -> bool:
        ...

    def IsOnCopperLayer(self) -> bool:
        ...

    def HasHole(self) -> bool:
        ...

    def IsTented(self) -> bool:
        ...

    def GetEffectiveShape(self, *args) -> "SHAPE":
        ...

    def GetEffectiveHoleShape(self) -> "SHAPE_SEGMENT":
        ...

    def GetParent(self) -> "BOARD_ITEM_CONTAINER":
        ...

    def GetParentFootprint(self) -> "BOARD_ITEM_CONTAINER":
        ...

    def HasLineStroke(self) -> bool:
        ...

    def GetStroke(self) -> "STROKE_PARAMS":
        ...

    def SetStroke(self, aStroke: "STROKE_PARAMS") -> None:
        ...

    def GetLayer(self) -> "PCB_LAYER_ID":
        ...

    def GetLayerSet(self) -> "LSET":
        ...

    def SetLayerSet(self, aLayers: "LSET") -> None:
        ...

    def SetLayer(self, aLayer: "PCB_LAYER_ID") -> None:
        ...

    def Duplicate(self) -> "BOARD_ITEM":
        ...

    def SwapItemData(self, aImage: "BOARD_ITEM"):
        ...

    def IsOnLayer(self, aLayer: "PCB_LAYER_ID") -> bool:
        ...

    def IsKnockout(self) -> bool:
        ...

    def SetIsKnockout(self, aKnockout: bool) -> None:
        ...

    def IsLocked(self) -> bool:
        ...

    def SetLocked(self, aLocked: bool) -> None:
        ...

    def DeleteStructure(self):
        ...

    def Move(self, aMoveVector: VECTOR2I):
        ...

    def Rotate(self, aRotCentre: VECTOR2I, aAngle: EDA_ANGLE) -> None:
        ...

    def Flip(self, aCentre: VECTOR2I, aFlipLeftRight: bool) -> None:
        ...

    def GetBoard(self, *args) -> "BOARD":
        ...

    def GetLayerName(self) -> str:
        ...

    def Duplicate(self) -> "BOARD_ITEM":
        ...

    def SetPos(self, p: VECTOR2I) -> None:
        ...
