from typing import Optional, Iterable, Any
import wx

EVT_DATAVIEW_ITEM_ACTIVATED: wx.EventType

class DataViewItem():
	def __init__(self, id: Optional[int]): ...

class DataViewTreeCtrl(wx.EventHandler):
	def SetItemText(self, item: DataViewItem, text: str) -> None: ...
	def ExpandChildren(self, node: DataViewItem) -> None: ...
	def Expand(self, node: DataViewItem) -> None: ...
	def DeleteAllItems(self) -> None: ...
	def DeleteChildren(self, node: DataViewItem) -> None: ...
	def AppendContainer(self, parent: DataViewItem, text: str, data: Any) -> DataViewItem: ...
	def AppendItem(self, parent: DataViewItem, text: str, data: Any) -> DataViewItem: ...
	def GetItemData(self, item: DataViewItem) -> Any: ...
	def GetSelections(self) -> Iterable[DataViewItem]: ...
